-- ============================================
-- SCRIPT DE CRIAÇÃO - SISTEMA MOTIVA
-- ============================================

-- 1. EQUIPE DE MANUTENÇÃO
CREATE TABLE equipe_manutencao (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    nome VARCHAR2(100) NOT NULL,

    CONSTRAINT pk_equipe_manutencao
        PRIMARY KEY (id)
);


-- 2. TRECHO DE RODOVIA
CREATE TABLE trecho_rodovia (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    quilometro_inicial NUMBER(10,2) NOT NULL,
    quilometro_final NUMBER(10,2) NOT NULL,
    nivel_vegetacao NUMBER(10,2) NOT NULL,
    nome VARCHAR2(100) NOT NULL,
    umido NUMBER(1) NOT NULL,
    monitorado NUMBER(1) NOT NULL,

    CONSTRAINT pk_trecho_rodovia
        PRIMARY KEY (id)
);


-- 3. INTERVENÇÃO OPERACIONAL
CREATE TABLE intervencao_operacional (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    tipo VARCHAR2(100) NOT NULL,
    descricao VARCHAR2(255),
    id_trecho NUMBER NOT NULL,

    CONSTRAINT pk_intervencao_operacional
        PRIMARY KEY (id),

    CONSTRAINT fk_intervencao_trecho
        FOREIGN KEY (id_trecho)
        REFERENCES trecho_rodovia(id)
);


-- 4. RELATÓRIO DE PRIORIDADE
CREATE TABLE relatorio_prioridade (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    qt_urgente NUMBER NOT NULL,
    qt_critico NUMBER NOT NULL,
    qt_atencao NUMBER NOT NULL,
    qt_normal NUMBER NOT NULL,
    resumo VARCHAR2(1000),

    CONSTRAINT pk_relatorio_prioridade
        PRIMARY KEY (id)
);